// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/y-sugiyama654/study-clean-architecture/internal/adapter/controller"
	"github.com/y-sugiyama654/study-clean-architecture/internal/adapter/gateway/postgres"
	"github.com/y-sugiyama654/study-clean-architecture/internal/infrastructure/system"
	"github.com/y-sugiyama654/study-clean-architecture/internal/infrastructure/web"
	"github.com/y-sugiyama654/study-clean-architecture/internal/usecase"
	"net/http"
)

// Injectors from wire.go:

func initializeHandler(db *sql.DB) http.Handler {
	taskRepository := postgres.NewTaskRepository(db)
	uuidGenerator := _wireUUIDGeneratorValue
	clock := _wireClockValue
	createTask := usecase.NewCreateTask(taskRepository, uuidGenerator, clock)
	getTask := usecase.NewGetTask(taskRepository)
	listTasks := usecase.NewListTasks(taskRepository)
	completeTask := usecase.NewCompleteTask(taskRepository, clock)
	taskController := controller.NewTaskController(createTask, getTask, listTasks, completeTask)
	handler := web.NewRouter(taskController)
	return handler
}

var (
	_wireUUIDGeneratorValue = system.UUIDGenerator{}
	_wireClockValue         = system.Clock{}
)
