// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package sqlcgen

import (
	"context"
	"time"
)

const insertActivity = `-- name: InsertActivity :exec

INSERT INTO task_activities (task_id, actor_id, action, occurred_at)
VALUES ($1, $2, $3, $4)
`

type InsertActivityParams struct {
	TaskID     string
	ActorID    string
	Action     string
	OccurredAt time.Time
}

// db/queries/activities.sql
func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) error {
	_, err := q.db.ExecContext(ctx, insertActivity,
		arg.TaskID,
		arg.ActorID,
		arg.Action,
		arg.OccurredAt,
	)
	return err
}
