// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"
)

type Task struct {
	ID          string
	OwnerID     string
	Title       string
	Description string
	Status      string
	CreatedAt   time.Time
	CompletedAt sql.NullTime
}

type TaskActivity struct {
	ID         int64
	TaskID     string
	ActorID    string
	Action     string
	OccurredAt time.Time
}
