// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const getTask = `-- name: GetTask :one
SELECT id, owner_id, title, description, status, created_at, completed_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listTasksByOwner = `-- name: ListTasksByOwner :many
SELECT id, owner_id, title, description, status, created_at, completed_at
FROM tasks
WHERE owner_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListTasksByOwner(ctx context.Context, ownerID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTask = `-- name: UpsertTask :exec

INSERT INTO tasks (id, owner_id, title, description, status, created_at, completed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE
SET title        = EXCLUDED.title,
    description  = EXCLUDED.description,
    status       = EXCLUDED.status,
    completed_at = EXCLUDED.completed_at
`

type UpsertTaskParams struct {
	ID          string
	OwnerID     string
	Title       string
	Description string
	Status      string
	CreatedAt   time.Time
	CompletedAt sql.NullTime
}

// db/queries/tasks.sql
func (q *Queries) UpsertTask(ctx context.Context, arg UpsertTaskParams) error {
	_, err := q.db.ExecContext(ctx, upsertTask,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.CreatedAt,
		arg.CompletedAt,
	)
	return err
}
